### ISSUE TITLE
Python 3.10+ compatibility

### ISSUE THREAD

**Issue by demberto** [sphinx-contrib/svgbob#1]
Please publish wheels for Python 3.10 and consider publishing wheels for 3.11 as well

**Comment by althonos** [comment]
@demberto : Done, you should now get Python 3.10 wheels for `v0.2.0`. I cannot provide wheels for Python 3.11 yet because the `manylinux2014` environment doesn't ship it.

**Comment by demberto** [comment]
Thank you :)

> because the `manylinux2014` environment doesn't ship it

You can pin the Python version to `3.11.0-rc2` if `setup-python` action is blocking it.
